# Generated by Django 4.2.7 on 2023-11-10 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ScannedData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('barcode', models.CharField(max_length=255)),
                ('other_column', models.CharField(max_length=255)),
                ('marked_column', models.CharField(blank=True, max_length=255, null=True)),
            ],
        ),
    ]
