# Generated by Django 4.2.7 on 2023-11-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scanner', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_number', models.CharField(max_length=255)),
                ('order_number', models.CharField(max_length=255)),
                ('description', models.CharField(max_length=255)),
                ('customer_name', models.CharField(max_length=255)),
                ('weight', models.FloatField()),
            ],
        ),
    ]
